#!/usr/bin/env bash

# Update autograder files
mkdir -p /autograder/code/submission/

cp -r /autograder/submission/* /autograder/code/submission/

cd /autograder/code
git pull

python3.6 run_tests.py > /autograder/source/results.json
